name: Release Package

on:
  push:
    branches:
      - main

jobs:
  build_mission_control:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build and push Mission Control Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/mission-control-ocp:latest
